// 30天小托福词汇库 - 1500个高频词汇
// 基于TOEFL Junior官方词汇表整理

const VOCABULARY_30_DAYS = {
  // ========== Day 1-10: 基础高频词汇 (A-D) ==========
  day1: [
    {word:"abandon",phonetic:"/əˈbændən/",meaning:"放弃，抛弃",emoji:"🚶‍♂️💨"},
    {word:"ability",phonetic:"/əˈbɪləti/",meaning:"能力，才能",emoji:"💪🧠"},
    {word:"absent",phonetic:"/ˈæbsənt/",meaning:"缺席的",emoji:"❌🏫"},
    {word:"absolute",phonetic:"/ˈæbsəluːt/",meaning:"绝对的",emoji:"💯"},
    {word:"absorb",phonetic:"/əbˈzɔːrb/",meaning:"吸收",emoji:"🧽💧"},
    {word:"abstract",phonetic:"/ˈæbstrækt/",meaning:"抽象的",emoji:"🎨🌀"},
    {word:"abundant",phonetic:"/əˈbʌndənt/",meaning:"丰富的",emoji:"🍎🍊🍇"},
    {word:"academic",phonetic:"/ˌækəˈdemɪk/",meaning:"学术的",emoji:"📚🎓"},
    {word:"accelerate",phonetic:"/əkˈseləreɪt/",meaning:"加速",emoji:"🚀⚡"},
    {word:"access",phonetic:"/ˈækses/",meaning:"进入，使用权",emoji:"🚪🔑"},
    {word:"accommodate",phonetic:"/əˈkɑːmədeɪt/",meaning:"容纳，适应",emoji:"🏨🛏️"},
    {word:"accomplish",phonetic:"/əˈkʌmplɪʃ/",meaning:"完成",emoji:"✅🏆"},
    {word:"accurate",phonetic:"/ˈækjərət/",meaning:"精确的",emoji:"🎯✓"},
    {word:"achieve",phonetic:"/əˈtʃiːv/",meaning:"达到，实现",emoji:"🏔️🏆"},
    {word:"acknowledge",phonetic:"/əkˈnɑːlɪdʒ/",meaning:"承认",emoji:"🙋‍♂️🙏"},
    {word:"acquire",phonetic:"/əˈkwaɪər/",meaning:"获得",emoji:"🎁✋"},
    {word:"adapt",phonetic:"/əˈdæpt/",meaning:"适应",emoji:"🦎🌿"},
    {word:"adequate",phonetic:"/ˈædɪkwət/",meaning:"足够的",emoji:"✅📏"},
    {word:"adjust",phonetic:"/əˈdʒʌst/",meaning:"调整",emoji:"🔧⚙️"},
    {word:"administer",phonetic:"/ədˈmɪnɪstər/",meaning:"管理",emoji:"📋👔"},
    {word:"admire",phonetic:"/ədˈmaɪər/",meaning:"钦佩",emoji:"👏😍"},
    {word:"admit",phonetic:"/ədˈmɪt/",meaning:"承认，准许",emoji:"🚪✅"},
    {word:"adopt",phonetic:"/əˈdɑːpt/",meaning:"采用，收养",emoji:"👶🏠"},
    {word:"advance",phonetic:"/ədˈvæns/",meaning:"前进",emoji:"➡️🚀"},
    {word:"advantage",phonetic:"/ədˈvæntɪdʒ/",meaning:"优势",emoji:"🏆⬆️"},
    {word:"adventure",phonetic:"/ədˈventʃər/",meaning:"冒险",emoji:"🏕️🗺️"},
    {word:"advertise",phonetic:"/ˈædvərtaɪz/",meaning:"做广告",emoji:"📢📺"},
    {word:"advice",phonetic:"/ədˈvaɪs/",meaning:"建议",emoji:"💡🗣️"},
    {word:"advocate",phonetic:"/ˈædvəkeɪt/",meaning:"提倡",emoji:"📣✊"},
    {word:"affect",phonetic:"/əˈfekt/",meaning:"影响",emoji:"🌊💫"},
    {word:"afford",phonetic:"/əˈfɔːrd/",meaning:"负担得起",emoji:"💰✅"},
    {word:"aggressive",phonetic:"/əˈɡresɪv/",meaning:"侵略的",emoji:"🐂💥"},
    {word:"agree",phonetic:"/əˈɡriː/",meaning:"同意",emoji:"🤝✅"},
    {word:"aid",phonetic:"/eɪd/",meaning:"帮助",emoji:"🚑🤝"},
    {word:"aim",phonetic:"/eɪm/",meaning:"目标",emoji:"🎯👁️"},
    {word:"alarm",phonetic:"/əˈlɑːrm/",meaning:"警报",emoji:"🚨🔔"},
    {word:"alert",phonetic:"/əˈlɜːrt/",meaning:"警觉的",emoji:"👀⚡"},
    {word:"allocate",phonetic:"/ˈæləkeɪt/",meaning:"分配",emoji:"🍕📊"},
    {word:"allow",phonetic:"/əˈlaʊ/",meaning:"允许",emoji:"✅🚦"},
    {word:"alter",phonetic:"/ˈɔːltər/",meaning:"改变",emoji:"✂️🔄"},
    {word:"alternative",phonetic:"/ɔːlˈtɜːrnətɪv/",meaning:"替代的",emoji:"🔄🛤️"},
    {word:"amateur",phonetic:"/ˈæmətər/",meaning:"业余的",emoji:"📷🎨"},
    {word:"amaze",phonetic:"/əˈmeɪz/",meaning:"使惊奇",emoji:"😲✨"},
    {word:"ambition",phonetic:"/æmˈbɪʃn/",meaning:"雄心",emoji:"🎯🔥"},
    {word:"analyze",phonetic:"/ˈænəlaɪz/",meaning:"分析",emoji:"🔬📊"},
    {word:"ancient",phonetic:"/ˈeɪnʃənt/",meaning:"古代的",emoji:"🏛️📜"},
    {word:"announce",phonetic:"/əˈnaʊns/",meaning:"宣布",emoji:"📢📰"},
    {word:"annoy",phonetic:"/əˈnɔɪ/",meaning:"惹恼",emoji:"😤🦟"},
    {word:"annual",phonetic:"/ˈænjuəl/",meaning:"每年的",emoji:"📅🎉"},
    {word:"anticipate",phonetic:"/ænˈtɪsɪpeɪt/",meaning:"预期",emoji:"🔮👀"}
  ],
  
  // ========== Day 2 ==========
  day2: [
    {word:"apparent",phonetic:"/əˈpærənt/",meaning:"明显的",emoji:"👁️✨"},
    {word:"appeal",phonetic:"/əˈpiːl/",meaning:"吸引，呼吁",emoji:"🧲📢"},
    {word:"appear",phonetic:"/əˈpɪr/",meaning:"出现",emoji:"👻✨"},
    {word:"appendix",phonetic:"/əˈpendɪks/",meaning:"附录",emoji:"📎📄"},
    {word:"appetite",phonetic:"/ˈæpɪtaɪt/",meaning:"食欲",emoji:"🍔🤤"},
    {word:"applaud",phonetic:"/əˈplɔːd/",meaning:"鼓掌",emoji:"👏👏"},
    {word:"appoint",phonetic:"/əˈpɔɪnt/",meaning:"任命",emoji:"👔📋"},
    {word:"appreciate",phonetic:"/əˈpriːʃieɪt/",meaning:"欣赏，感激",emoji:"🙏❤️"},
    {word:"approach",phonetic:"/əˈproʊtʃ/",meaning:"接近，方法",emoji:"🏃‍♂️🎯"},
    {word:"appropriate",phonetic:"/əˈproʊpriət/",meaning:"适当的",emoji:"✅👌"},
    {word:"approve",phonetic:"/əˈpruːv/",meaning:"批准",emoji:"✅📋"},
    {word:"approximate",phonetic:"/əˈprɑːksɪmət/",meaning:"大约的",emoji:"≈📊"},
    {word:"arbitrary",phonetic:"/ˈɑːrbətreri/",meaning:"任意的",emoji:"🎲🤷"},
    {word:"argue",phonetic:"/ˈɑːrɡjuː/",meaning:"争论",emoji:"🗣️💢"},
    {word:"arise",phonetic:"/əˈraɪz/",meaning:"产生，上升",emoji:"⬆️🌅"},
    {word:"arrange",phonetic:"/əˈreɪndʒ/",meaning:"安排",emoji:"📅✅"},
    {word:"arrest",phonetic:"/əˈrest/",meaning:"逮捕",emoji:"👮‍♂️🚨"},
    {word:"arrival",phonetic:"/əˈraɪvl/",meaning:"到达",emoji:"🛬📍"},
    {word:"article",phonetic:"/ˈɑːrtɪkl/",meaning:"文章，物品",emoji:"📰📦"},
    {word:"artificial",phonetic:"/ˌɑːrtɪˈfɪʃl/",meaning:"人造的",emoji:"🤖🎭"},
    {word:"aspect",phonetic:"/ˈæspekt/",meaning:"方面",emoji:"🔲📐"},
    {word:"assemble",phonetic:"/əˈsembl/",meaning:"集合，组装",emoji:"🔧🧩"},
    {word:"assert",phonetic:"/əˈsɜːrt/",meaning:"断言",emoji:"💬✊"},
    {word:"assess",phonetic:"/əˈses/",meaning:"评估",emoji:"📊✅"},
    {word:"assign",phonetic:"/əˈsaɪn/",meaning:"分配，指派",emoji:"📋👉"},
    {word:"assist",phonetic:"/əˈsɪst/",meaning:"协助",emoji:"🤝🆘"},
    {word:"associate",phonetic:"/əˈsoʊʃieɪt/",meaning:"联系，同事",emoji:"🔗👥"},
    {word:"assume",phonetic:"/əˈsuːm/",meaning:"假设",emoji:"🤔💭"},
    {word:"assure",phonetic:"/əˈʃʊr/",meaning:"保证",emoji:"🤝✅"},
    {word:"astonish",phonetic:"/əˈstɑːnɪʃ/",meaning:"使惊讶",emoji:"😲🤯"},
    {word:"attach",phonetic:"/əˈtætʃ/",meaning:"附上，依恋",emoji:"📎❤️"},
    {word:"attack",phonetic:"/əˈtæk/",meaning:"攻击",emoji:"⚔️💥"},
    {word:"attempt",phonetic:"/əˈtempt/",meaning:"尝试",emoji:"🎯🏃"},
    {word:"attend",phonetic:"/əˈtend/",meaning:"参加，照顾",emoji:"📍👂"},
    {word:"attitude",phonetic:"/ˈætɪtuːd/",meaning:"态度",emoji:"🧠💭"},
    {word:"attract",phonetic:"/əˈtrækt/",meaning:"吸引",emoji:"🧲✨"},
    {word:"attribute",phonetic:"/əˈtrɪbjuːt/",meaning:"属性，归因",emoji:"🏷️➡️"},
    {word:"audience",phonetic:"/ˈɔːdiəns/",meaning:"观众",emoji:"👥🎭"},
    {word:"authority",phonetic:"/əˈθɔːrəti/",meaning:"权威",emoji:"👑⚖️"},
    {word:"automatic",phonetic:"/ˌɔːtəˈmætɪk/",meaning:"自动的",emoji:"🤖⚙️"},
    {word:"available",phonetic:"/əˈveɪləbl/",meaning:"可用的",emoji:"✅📦"},
    {word:"average",phonetic:"/ˈævərɪdʒ/",meaning:"平均的",emoji:"📊➗"},
    {word:"avoid",phonetic:"/əˈvɔɪd/",meaning:"避免",emoji:"🚫↔️"},
    {word:"aware",phonetic:"/əˈwer/",meaning:"意识到的",emoji:"🧠💡"},
    {word:"awful",phonetic:"/ˈɔːfl/",meaning:"糟糕的",emoji:"😫👎"},
    {word:"awkward",phonetic:"/ˈɔːkwərd/",meaning:"尴尬的",emoji:"😅🙃"},
    {word:"background",phonetic:"/ˈbækɡraʊnd/",meaning:"背景",emoji:"🖼️📚"},
    {word:"balance",phonetic:"/ˈbæləns/",meaning:"平衡",emoji:"⚖️🏃"},
    {word:"ban",phonetic:"/bæn/",meaning:"禁止",emoji:"🚫🚷"},
    {word:"barrier",phonetic:"/ˈbæriər/",meaning:"障碍",emoji:"🚧🛑"}
  ]
};

// 导出模块
if (typeof module !== 'undefined' && module.exports) {
  module.exports = VOCABULARY_30_DAYS;
}